### PR TITLE
Update for new unified buffer interface

### PR DESCRIPTION
**Pull request by norabarlow**
Update mapper for new unified buffer interface.

Adds CoreIR pass to remove muxes with one input.

### CODE REVIEW

**Comment by Kuree** [comment]
When will halide-to-hardware get updated that matches with this change?

**Comment by norabarlow** [comment]
It's on the hwbuffer_jeff branch. Do you want it merged with master?

**Comment by Kuree** [comment]
Garnetflow pulls from the master branch of halide-to-hardware. If these two are out of sync, it's going to fail the end-to-end flow test. I'd prefer to have everything in place when we do the merge.

**Comment by norabarlow** [comment]
Unified buffer/lakelib have been merged into master: https://github.com/StanfordAHA/Halide-to-Hardware/pull/74

**Comment by norabarlow** [comment]
But https://github.com/joyliu37/BufferMapping/pull/10 needs to be merged first.

**Comment by Kuree** [comment]
Thanks. Let me know once it's ready to merge.

**Comment by norabarlow** [comment]
Can we merge this?

**Review by Kuree — APPROVED** [review]

**Pull request merged**
